### Exercici 1
###### Descarrega el dataset adjunt de dades oficials de la UEFA i selecciona un atribut del conjunt de dades. Calcula el p-valor i digues si rebutja la hipòtesi nul·la agafant un alfa de 5%.

In [1]:
import pandas as pd
import warnings
from scipy import stats

warnings.filterwarnings('ignore') # Ignora los mensajes de error.

In [2]:
df = pd.read_csv('UEFA.csv', sep=';', encoding='latin1')
df

,Rk,Squad,Country,LgRk,MP,W,D,L,GF,GA,...,Pts,Pts/G,xG,xGA,xGD,xGD/90,Last 5,Attendance,Top Team Scorer,Goalkeeper
0,1,Manchester City,ENG,1,37,28,6,3,96,24,...,90,2.43,86.1,26.8,59.3,1.60,W W W W D,52739,Kevin De Bruyne - 15,Ederson
1,2,Liverpool,ENG,2,36,26,8,2,89,24,...,86,2.39,84.6,33.1,51.4,1.43,W W W D W,53367,Mohamed Salah - 22,Alisson
2,3,Real Madrid,ESP,1,37,26,7,4,80,31,...,85,2.30,73.0,45.8,27.2,0.73,W W L W D,40624,Karim Benzema - 27,Thibaut Courtois
3,4,Bayern Munich,GER,1,34,24,5,5,97,37,...,77,2.26,88.1,37.1,51.0,1.50,W W L D D,33176,Robert Lewandowski - 35,Manuel Neuer
4,5,Paris S-G,FRA,1,37,25,8,4,85,36,...,83,2.24,71.6,38.1,33.4,0.90,W D D D W,41188,Kylian Mbappé - 25,Keylor Navas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,94,Bordeaux,FRA,20,37,5,13,19,48,89,...,28,0.76,41.3,68.5,-27.2,-0.73,D L L L D,22083,Hwang Ui-jo - 11,Benoît Costil
94,95,Venezia,ITA,20,37,6,8,23,34,69,...,26,0.70,35.4,70.5,-35.1,-0.95,L L L W D,6705,Thomas Henry - 9,Sergio Romero
95,96,Watford,ENG,19,37,6,5,26,33,75,...,23,0.62,37.8,64.1,-26.3,-0.71,L L L D L,20614,Emmanuel Dennis - 10,Ben Foster
96,97,Norwich City,ENG,20,37,5,7,25,23,79,...,22,0.59,33.0,73.3,-40.4,-1.09,L L L L D,26826,Teemu Pukki - 11,Tim Krul
97,98,Greuther Fürth,GER,18,34,3,9,22,28,82,...,18,0.53,30.7,60.3,-29.6,-0.87,D L D L L,7672,Branimir Hrgota - 9,Sascha Burchert

In [3]:
df.columns

Index(['Rk', 'Squad', 'Country', 'LgRk', 'MP', 'W', 'D', 'L', 'GF', 'GA', 'GD',
       'Pts', 'Pts/G', 'xG', 'xGA', 'xGD', 'xGD/90', 'Last 5', 'Attendance',
       'Top Team Scorer', 'Goalkeeper'],
      dtype='object')

Elijo la variable de 'Pts/G', que representa los puntos por partido.

PASO 1, Establezco una hipótesis nula y una alternativa

- Ho: Los datos no se ajustan a una distribución normal
- H1: Los datos vienen de una distribución normal
- Alpha: 5%

In [4]:
data_points = df['Pts/G'] #Visualizo la variable.
data_points

0     2.43
1     2.39
2     2.30
3     2.26
4     2.24
      ...
93    0.76
94    0.70
95    0.62
96    0.59
97    0.53
Name: Pts/G, Length: 98, dtype: float64

In [5]:
paises = df.groupby(df['Country']).count() # Quiero saber en ámbito de los datos registrados
print(paises)

         Rk  Squad  LgRk  MP   W   D   L  GF  GA  GD  Pts  Pts/G  xG  xGA  \
Country
ENG      20     20    20  20  20  20  20  20  20  20   20     20  20   20
ESP      20     20    20  20  20  20  20  20  20  20   20     20  20   20
FRA      20     20    20  20  20  20  20  20  20  20   20     20  20   20
GER      18     18    18  18  18  18  18  18  18  18   18     18  18   18
ITA      20     20    20  20  20  20  20  20  20  20   20     20  20   20

         xGD  xGD/90  Last 5  Attendance  Top Team Scorer  Goalkeeper
Country
ENG       20      20      20          20               20          20
ESP       20      20      20          20               20          20
FRA       20      20      20          20               20          20
GER       18      18      18          18               18          18
ITA       20      20      20          20               20          20

PASO 2, la recopilación de datos son de 98 registros de equipos de Europa. Los datos de la columna seleccionada son numéricos.

PASO 3, realizo la prueba estadística shapiro Wilks para probar la normalidad de la distribución.

In [6]:
from scipy.stats import shapiro
estadistico, p_value = shapiro(data_points)
print('Estadistico=%.3f, p_value=%.3f' % (estadistico, p_value))

Estadistico=0.972, p_value=0.035

PASO 4, En este caso, el pvalue, indica que está por debajo de 0,05 y  por lo tanto sí podemos rechazar la hipótesis nula y dar por confirmada que los datos de la variable 'Pts/G', vienen de una distribución normal.

### - Exercici 2
###### Amb el mateix dataset selecciona dos altres atributs del conjunt de dades. Calcula els p-valors i digues si rebutgen la hipòtesi nul·la agafant un alfa de 5%.

Elijo la variable de 'Rk'y 'W', que representa posición del equipo dentro de la liga y partidos ganados.

PASO 1, Establezco una hipótesis nula y una alternativa

- H0: las medias de las muestras son iguales.
- H1: las medias de las muestras son desiguales.

- Alpha: 5%

PASO 2: Visualizo las variables y los datos son numéricos.

In [7]:
columnas = df[['Rk', 'W']]
columnas

    Rk   W
0    1  28
1    2  26
2    3  26
3    4  24
4    5  25
..  ..  ..
93  94   5
94  95   6
95  96   6
96  97   5
97  98   3

[98 rows x 2 columns]

PASO 3, realizo la prueba estadística T de Student para probar si las muestras son significativamente diferentes.

In [8]:
from scipy.stats import ttest_ind
# Establezco las dos muestras
muestra1 = df['Rk']
muestra2 = df['W']
# Realizo la prueba t Student

estadistico, p_value = ttest_ind(muestra1, muestra2)
print('Estadistico=%.3f, p_value=%.3f' % (estadistico, p_value))

Estadistico=12.303, p_value=0.000

PASO 4, En este caso, el pvalue, indica que está por debajo de 0,05 y por lo tanto sí podemos rechazar la hipótesis nula y dar por confirmada que las medias de las muestras son desiguales.

### - Exercici 3
###### Continua amb el conjunt de dades adjunt i selecciona tres atributs del conjunt de dades. Calcula el p-valor i digues si rebutja la hipòtesi nul·la agafant un alfa de 5%.

Elijo la variable de 'Rk', la variable de 'W' y la variable de 'GF'  que representan, ranking de liga, partidos ganados y goles a favor.

PASO 1, Establezco una hipótesis nula y una alternativa

- H0: las medias de las muestras son iguales.
- H1: una o más de las medias de las muestras son desiguales.
- Alpha: 5%

PASO 2: Visualizo las variables y los datos son numéricos.

In [9]:
columnas3 = df[['Rk', 'W', 'GF']]
columnas3

    Rk   W  GF
0    1  28  96
1    2  26  89
2    3  26  80
3    4  24  97
4    5  25  85
..  ..  ..  ..
93  94   5  48
94  95   6  34
95  96   6  33
96  97   5  23
97  98   3  28

[98 rows x 3 columns]

PASO 3, realizo la prueba estadística ANOVA para probar si las muestras son significativamente diferentes.

In [10]:
from scipy.stats import f_oneway
# Establezco las dos muestras
variable1 = df['Rk']
variable2 = df['W']
variable3 = df['GF']
# Realizo la prueba ANOVA

estadistico, p_value = f_oneway(variable1,variable2,variable3)
print('Estadistico=%.3f, p_value=%.3f' % (estadistico, p_value))

Estadistico=120.291, p_value=0.000

PASO 4, En este caso, el pvalue, indica que está por debajo de 0,05 y por lo tanto sí podemos rechazar la hipótesis nula y dar por confirmada que una o más de las medias de las muestras no son iguales.